spring.application.name=SMBS backend

spring.security.enabled=false

spring.datasource.url=jdbc:mysql://mysql-1373edcd-reshrajchaudhary009-1bbb.a.aivencloud.com:27533/defaultdb?ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_PASSWORD_HERE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=${PORT:8080}
